<?php


namespace frontend\controllers;


use yii\web\Controller;

class MyController extends Controller
{
    public function actionIndex($id = null)
    {
        $hi = 'Hello, World';
        $names= ['Ivanov', 'Petrov'];
        if (!$id) $id = 'test';

        return $this->render('index',['hello'=>$hi, 'names'=>$names, 'id'=>$id ]);
    }

    public function actionBlogPost()
    {
        return 'Blog Post'; // TODO: Change the autogenerated stub
    }
}